-- SUPERSEDED — do not run this file.
-- This used to reopen `users` with `create policy "users_read" ... using (true)`,
-- which is why raw REST reads of `users` were fully public in production.
-- Referral lookup is now served by the narrow, security-definer RPC in
-- referral_lookup_rpc_v2.sql (public.ngmy_lookup_referrer), which returns only
-- the single matching row's non-sensitive columns instead of opening the table.
