import 'package:flutter/material.dart';

/// Visual layout for rendered menu pages.
enum NgmyMenuLayoutStyle {
  ornateDots,
  fineDining,
  modernCards,
  minimalLine,
  bistroWarm,
  artDeco,
  neonPanel,
  magazineColumn,
  ticketStrip,
  priceRibbon,
  sidebarAccent,
  polaroidFrame,
  tableGrid,
}

class NgmyMenuTemplate {
  const NgmyMenuTemplate({
    required this.id,
    required this.name,
    required this.category,
    required this.bgStart,
    required this.bgEnd,
    required this.accent,
    required this.textPrimary,
    required this.textSecondary,
    required this.cardBg,
    required this.layout,
    this.headerStyle = 'center',
    this.subtitle = '',
  });

  final String id;
  final String name;
  final String category;
  final String subtitle;
  final Color bgStart;
  final Color bgEnd;
  final Color accent;
  final Color textPrimary;
  final Color textSecondary;
  final Color cardBg;
  final NgmyMenuLayoutStyle layout;
  final String headerStyle;
}

const List<NgmyMenuTemplate> kNgmyMenuTemplates = [
  NgmyMenuTemplate(
    id: 'midnight_gold',
    name: 'Midnight Gold',
    category: 'Luxury',
    subtitle: 'Black velvet · gold foil',
    bgStart: Color(0xFF050505),
    bgEnd: Color(0xFF14100A),
    accent: Color(0xFFD4AF37),
    textPrimary: Color(0xFFFFF8E7),
    textSecondary: Color(0xFFC9B896),
    cardBg: Color(0xFF0C0A08),
    layout: NgmyMenuLayoutStyle.ornateDots,
    headerStyle: 'ornate',
  ),
  NgmyMenuTemplate(
    id: 'marble_elegance',
    name: 'Marble Elegance',
    category: 'Luxury',
    subtitle: 'Cream marble · serif',
    bgStart: Color(0xFFF5F0EB),
    bgEnd: Color(0xFFE8E0D8),
    accent: Color(0xFF8B7355),
    textPrimary: Color(0xFF2C2419),
    textSecondary: Color(0xFF6B5D4F),
    cardBg: Color(0xFFFFFBF7),
    layout: NgmyMenuLayoutStyle.fineDining,
    headerStyle: 'serif',
  ),
  NgmyMenuTemplate(
    id: 'champagne_night',
    name: 'Champagne Night',
    category: 'Luxury',
    subtitle: 'Celebration · sparkle',
    bgStart: Color(0xFF1A1520),
    bgEnd: Color(0xFF2D2438),
    accent: Color(0xFFE8C4A0),
    textPrimary: Color(0xFFFFF5EB),
    textSecondary: Color(0xFFD4C4B0),
    cardBg: Color(0xFF221C2A),
    layout: NgmyMenuLayoutStyle.artDeco,
    headerStyle: 'ornate',
  ),
  NgmyMenuTemplate(
    id: 'steakhouse_prime',
    name: 'Steakhouse Prime',
    category: 'Fine dining',
    subtitle: 'Bold · leather dark',
    bgStart: Color(0xFF1C1210),
    bgEnd: Color(0xFF2A1814),
    accent: Color(0xFFC9A227),
    textPrimary: Color(0xFFF5EDE4),
    textSecondary: Color(0xFFB8A090),
    cardBg: Color(0xFF241816),
    layout: NgmyMenuLayoutStyle.fineDining,
    headerStyle: 'serif',
  ),
  NgmyMenuTemplate(
    id: 'sakura_zen',
    name: 'Sakura Zen',
    category: 'Fine dining',
    subtitle: 'Japanese minimal',
    bgStart: Color(0xFF0F0E0E),
    bgEnd: Color(0xFF1A1818),
    accent: Color(0xFFDC2626),
    textPrimary: Color(0xFFFAFAF9),
    textSecondary: Color(0xFFA8A29E),
    cardBg: Color(0xFF161414),
    layout: NgmyMenuLayoutStyle.minimalLine,
    headerStyle: 'minimal',
  ),
  NgmyMenuTemplate(
    id: 'rooftop_sky',
    name: 'Rooftop Sky',
    category: 'Modern',
    subtitle: 'Gradient · skyline',
    bgStart: Color(0xFF0F172A),
    bgEnd: Color(0xFF1E3A5F),
    accent: Color(0xFF38BDF8),
    textPrimary: Color(0xFFF0F9FF),
    textSecondary: Color(0xFF94A3B8),
    cardBg: Color(0xFF152238),
    layout: NgmyMenuLayoutStyle.modernCards,
  ),
  NgmyMenuTemplate(
    id: 'trattoria_roma',
    name: 'Trattoria Roma',
    category: 'Classic',
    subtitle: 'Warm Italian',
    bgStart: Color(0xFF3D2314),
    bgEnd: Color(0xFF5C3318),
    accent: Color(0xFFF4A460),
    textPrimary: Color(0xFFFFF8F0),
    textSecondary: Color(0xFFE8D4C0),
    cardBg: Color(0xFF4A2E1C),
    layout: NgmyMenuLayoutStyle.bistroWarm,
  ),
  NgmyMenuTemplate(
    id: 'ocean_grill',
    name: 'Ocean Grill',
    category: 'Modern',
    subtitle: 'Coastal · fresh',
    bgStart: Color(0xFF042F2E),
    bgEnd: Color(0xFF0F4C5C),
    accent: Color(0xFF5EEAD4),
    textPrimary: Color(0xFFECFEFF),
    textSecondary: Color(0xFF99F6E4),
    cardBg: Color(0xFF0A3D3C),
    layout: NgmyMenuLayoutStyle.modernCards,
  ),
  NgmyMenuTemplate(
    id: 'botanical_garden',
    name: 'Botanical Garden',
    category: 'Organic',
    subtitle: 'Garden café',
    bgStart: Color(0xFF14532D),
    bgEnd: Color(0xFF166534),
    accent: Color(0xFFBBF7D0),
    textPrimary: Color(0xFFF0FDF4),
    textSecondary: Color(0xFF86EFAC),
    cardBg: Color(0xFF15803D),
    layout: NgmyMenuLayoutStyle.bistroWarm,
  ),
  // —— New distinct layouts (different from originals above) ——
  NgmyMenuTemplate(
    id: 'velvet_neon',
    name: 'Velvet Neon',
    category: 'Modern',
    subtitle: 'Night club · glow panels',
    bgStart: Color(0xFF0A0014),
    bgEnd: Color(0xFF1A0A2E),
    accent: Color(0xFFFF2D95),
    textPrimary: Color(0xFFFDF4FF),
    textSecondary: Color(0xFFE879F9),
    cardBg: Color(0xFF2E1065),
    layout: NgmyMenuLayoutStyle.neonPanel,
    headerStyle: 'neon',
  ),
  NgmyMenuTemplate(
    id: 'copper_forge',
    name: 'Copper Forge',
    category: 'Classic',
    subtitle: 'Industrial · ribbon prices',
    bgStart: Color(0xFF1A120C),
    bgEnd: Color(0xFF2D1F14),
    accent: Color(0xFFCD7F32),
    textPrimary: Color(0xFFF5E6D3),
    textSecondary: Color(0xFFC4A882),
    cardBg: Color(0xFF3D2A1A),
    layout: NgmyMenuLayoutStyle.priceRibbon,
    headerStyle: 'industrial',
  ),
  NgmyMenuTemplate(
    id: 'pacific_sidebar',
    name: 'Pacific Sidebar',
    category: 'Modern',
    subtitle: 'Coastal · accent rail',
    bgStart: Color(0xFF0C1929),
    bgEnd: Color(0xFF132337),
    accent: Color(0xFF22D3EE),
    textPrimary: Color(0xFFF0FDFA),
    textSecondary: Color(0xFF67E8F9),
    cardBg: Color(0xFF1E3A4F),
    layout: NgmyMenuLayoutStyle.sidebarAccent,
  ),
  NgmyMenuTemplate(
    id: 'drive_in_retro',
    name: 'Drive-In Retro',
    category: 'Classic',
    subtitle: '50s tickets · stripes',
    bgStart: Color(0xFF2D1B4E),
    bgEnd: Color(0xFF4A1942),
    accent: Color(0xFFFF6B35),
    textPrimary: Color(0xFFFFF7ED),
    textSecondary: Color(0xFFFDBA74),
    cardBg: Color(0xFF3D2654),
    layout: NgmyMenuLayoutStyle.ticketStrip,
    headerStyle: 'retro',
  ),
  NgmyMenuTemplate(
    id: 'parisian_cafe',
    name: 'Parisian Café',
    category: 'Classic',
    subtitle: 'Magazine · red trim',
    bgStart: Color(0xFFFFF9F5),
    bgEnd: Color(0xFFF5EBE0),
    accent: Color(0xFFB91C1C),
    textPrimary: Color(0xFF1C1917),
    textSecondary: Color(0xFF78716C),
    cardBg: Color(0xFFFFFBF7),
    layout: NgmyMenuLayoutStyle.magazineColumn,
    headerStyle: 'magazine',
  ),
  NgmyMenuTemplate(
    id: 'tokyo_stack',
    name: 'Tokyo Stack',
    category: 'Fine dining',
    subtitle: 'Layered cards · izakaya',
    bgStart: Color(0xFF0C0A09),
    bgEnd: Color(0xFF1C1917),
    accent: Color(0xFFEF4444),
    textPrimary: Color(0xFFFAFAF9),
    textSecondary: Color(0xFFA8A29E),
    cardBg: Color(0xFF292524),
    layout: NgmyMenuLayoutStyle.polaroidFrame,
    headerStyle: 'stack',
  ),
  NgmyMenuTemplate(
    id: 'desert_mirage',
    name: 'Desert Mirage',
    category: 'Organic',
    subtitle: 'Terracotta · framed items',
    bgStart: Color(0xFF431407),
    bgEnd: Color(0xFF7C2D12),
    accent: Color(0xFFFBBF24),
    textPrimary: Color(0xFFFFF7ED),
    textSecondary: Color(0xFFFED7AA),
    cardBg: Color(0xFF9A3412),
    layout: NgmyMenuLayoutStyle.polaroidFrame,
  ),
  NgmyMenuTemplate(
    id: 'nordic_table',
    name: 'Nordic Table',
    category: 'Modern',
    subtitle: 'Grid rows · ice blue',
    bgStart: Color(0xFFEFF6FF),
    bgEnd: Color(0xFFDBEAFE),
    accent: Color(0xFF0369A1),
    textPrimary: Color(0xFF0C4A6E),
    textSecondary: Color(0xFF64748B),
    cardBg: Color(0xFFFFFFFF),
    layout: NgmyMenuLayoutStyle.tableGrid,
    headerStyle: 'grid',
  ),
  NgmyMenuTemplate(
    id: 'mediterranean_tile',
    name: 'Mediterranean Tile',
    category: 'Classic',
    subtitle: 'Azure tiles · hand-drawn',
    bgStart: Color(0xFF1E3A8A),
    bgEnd: Color(0xFF1D4ED8),
    accent: Color(0xFFFDE68A),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFBFDBFE),
    cardBg: Color(0xFF2563EB),
    layout: NgmyMenuLayoutStyle.ticketStrip,
    headerStyle: 'tile',
  ),
  NgmyMenuTemplate(
    id: 'jazz_lounge',
    name: 'Jazz Lounge',
    category: 'Luxury',
    subtitle: 'Emerald · neon glow',
    bgStart: Color(0xFF052E16),
    bgEnd: Color(0xFF14532D),
    accent: Color(0xFFFACC15),
    textPrimary: Color(0xFFECFDF5),
    textSecondary: Color(0xFF86EFAC),
    cardBg: Color(0xFF166534),
    layout: NgmyMenuLayoutStyle.neonPanel,
    headerStyle: 'jazz',
  ),
];

NgmyMenuTemplate ngmyMenuTemplateById(String id) {
  final normalized = switch (id) {
    'ivory_minimal' => 'nordic_table',
    _ => id,
  };
  return kNgmyMenuTemplates.firstWhere(
    (t) => t.id == normalized,
    orElse: () => kNgmyMenuTemplates.first,
  );
}

List<NgmyMenuTemplate> ngmyMenuTemplatesForCategory(String category) {
  if (category == 'all') return kNgmyMenuTemplates;
  return kNgmyMenuTemplates.where((t) => t.category.toLowerCase() == category.toLowerCase()).toList();
}
