/// Romantic ideas for Fun & Games → Love (Next, Keep, Date).
class NgmyLoveContent {
  NgmyLoveContent._();

  static const int ideaCount = 50;

  static const List<String> nextIdeas = [
    'Meet for iced coffee at a cozy corner café — keep the first chat light and warm.',
    'Grab matcha lattes and take a slow walk through a pretty downtown street.',
    'Share a fruit smoothie at a sunny outdoor patio and people-watch together.',
    'Try a dessert café — split a slice of cake and talk about favorite memories.',
    'Meet for hot chocolate on a cool evening; bring a light jacket for them if it is chilly.',
    'Visit a bookstore café, pick a book each, and swap why you chose it.',
    'Get bubble tea with two straws and play “this or that” questions.',
    'Meet at a farmers market, sample something small, and stroll the stalls.',
    'Share artisan pizza at a small Italian spot — split a margherita and a salad.',
    'Try tacos from a popular local truck, then sit in a park nearby.',
    'Breakfast date: pancakes, fresh juice, and no rush to leave the table.',
    'Sushi lunch at a calm spot — order a few rolls to share and one surprise roll.',
    'Meet for fresh lemonade and sandwiches at a riverside bench.',
    'Visit a tea house for jasmine tea and quiet conversation.',
    'Grab gelato and walk through a garden or campus green.',
    'Try a food hall: each pick one dish and taste from both plates.',
    'Meet for soup and bread at a homestyle diner — comfort food builds comfort.',
    'Share a charcuterie board and sparkling water at a wine-free bistro patio.',
    'Visit a donut shop early and bring one extra for “later.”',
    'Meet for acai bowls and talk about dreams, not just schedules.',
    'Try a juice bar smoothie bowl after a short morning hike together.',
    'Meet at a rooftop café at golden hour — photos optional, presence required.',
    'Share pasta at a candle-free lunch spot; save candles for another time.',
    'Visit a bakery, choose two pastries, and rank them honestly.',
    'Meet for chai and samosas at a cozy Indian café.',
    'Try Korean street snacks at a small shop and share everything.',
    'Meet for fresh spring rolls and iced tea — light, fresh, easy to talk.',
    'Share fish and chips by the water if you live near a coast or lake.',
    'Visit a plant-based café even if you are not vegan — curiosity is attractive.',
    'Meet for espresso and cannoli — short, sweet, memorable.',
    'Try a build-your-own bowl place; compare creations like a fun contest.',
    'Meet at a dog-friendly patio if one of you has a calm pet — instant icebreaker.',
    'Share crepes — one savory, one sweet — at a French-style café.',
    'Visit a chocolate shop for truffles and a five-minute tasting ritual.',
    'Meet for pho or ramen; warm bowls make honest conversation easier.',
    'Try a Mediterranean platter with hummus, pita, and grilled vegetables.',
    'Meet for iced hibiscus tea and a shared salad on a shaded terrace.',
    'Visit a comic shop with a café inside — laugh together early.',
    'Share wings or sliders at a sports bar during an early, quiet hour.',
    'Meet for cronuts or fresh croissants and talk about childhood favorites.',
    'Try a pop-up food event — exploring something new together bonds fast.',
    'Meet for coconut water and tropical fruit after a beach walk.',
    'Share a cheese toastie and tomato soup on a rainy afternoon.',
    'Visit a flower market and buy one stem each for the other.',
    'Meet for lavender latte and shortbread at a calm neighborhood spot.',
    'Try handmade pasta at a chef-owned trattoria — dress cute but casual.',
    'Meet for boba and board games at a café that hosts game nights.',
    'Share a picnic basket you prepared: sandwiches, grapes, and a kind note.',
    'Visit a sunset viewpoint with thermoses of cider or sparkling juice.',
    'End the first meet with a clear “I enjoyed today” — confidence is romantic.',
  ];

  static const List<String> keepIdeas = [
    'Send a voice note saying one specific thing you appreciated about them today.',
    'Plan a no-phone hour together — phones face down, eyes on each other.',
    'Remember a small detail they mentioned and bring it up later; it shows you listen.',
    'Compliment their character, not only their appearance — depth keeps hearts close.',
    'Schedule a weekly check-in: “How are we feeling about us?”',
    'Share a playlist of songs that remind you of them — three tracks is enough.',
    'Apologize quickly when you are wrong; pride is the enemy of closeness.',
    'Celebrate their wins loudly, even the small ones — promotion, recipe, good day.',
    'Ask “What would make this week easier for you?” and follow through once.',
    'Leave a handwritten note in their bag, book, or on the mirror.',
    'Plan surprise comfort: their favorite snack after a hard day.',
    'Touch base mid-day with a kind text — not demanding, just warm.',
    'Learn one thing they care about and ask a thoughtful question about it.',
    'Defend them kindly in public; loyalty builds trust.',
    'Create a shared inside joke — intimacy loves private language.',
    'Book something to look forward to: concert, class, weekend trip.',
    'Practice patience when they need space; trust is quiet confidence.',
    'Cook or order their favorite meal without being asked.',
    'Take photos together that are candid, not only posed perfection.',
    'Say thank you for ordinary things: listening, driving, patience.',
    'Introduce them proudly to friends — belonging matters.',
    'Keep promises small and large; reliability is romance in action.',
    'Flirt after you are comfortable — playfulness keeps sparks alive.',
    'Ask about their family with genuine curiosity, not interrogation.',
    'Share your feelings with calm words instead of guessing games.',
    'Plan a tech-free walk and hold hands if you both want that.',
    'Respect their boundaries without making them explain twice.',
    'Send a meme or reel that made you think of them — light connection counts.',
    'Celebrate anniversaries of small moments: first coffee, first laugh.',
    'Offer help before they have to ask — dishes, errands, ride.',
    'Speak their love language: time, words, gifts, acts, touch — learn which lands.',
    'Do not weaponize the past in arguments; solve today’s issue today.',
    'Plan a double date with friends who bring good energy.',
    'Write three things you love about them and read one aloud.',
    'Protect their reputation online and offline.',
    'Wake up early once to make breakfast — effort is attractive.',
    'Listen without fixing unless they ask for advice.',
    'Share goals and ask how you can support, not control.',
    'Laugh at yourselves when plans fail — resilience is sexy.',
    'Keep dating each other: dress up for no reason sometimes.',
    'Remember important dates in your calendar with alerts.',
    'Give them the last bite if they love it — generosity in small things.',
    'Plan a cozy movie night with their favorite blanket rules.',
    'Tell them when you are proud of how they handled something hard.',
    'Be consistent with good morning and good night kindness.',
    'Create a shared tradition: Sunday brunch, Friday playlist, monthly adventure.',
    'Forgive fast when intent was good — hold grace like a gift.',
    'Ask for what you need clearly instead of testing them.',
    'Surprise them with flowers, a plant, or something living and hopeful.',
    'Dream aloud about the future together — direction feels safe.',
    'Choose them again today — love is a daily decision, not a one-time event.',
  ];

  static const List<String> dateIdeas = [
    'Stargazing picnic with blankets, thermoses, and a constellation app.',
    'Couples pottery or paint-and-sip night — laugh at the masterpieces.',
    'Sunset kayak or paddleboat if you are both comfortable on water.',
    'Dress up for dinner at a place with live acoustic music.',
    'Home movie marathon: their pick, your pick, popcorn, dim lights.',
    'Botanical garden walk with a camera and zero rush.',
    'Rooftop or hilltop picnic at golden hour with sparkling juice.',
    'Dance class intro: salsa, bachata, or swing — beginners welcome.',
    'Visit a museum and choose one artwork that represents your mood.',
    'Cook a new recipe together — assign roles: chef and sous-chef.',
    'Ice skating or roller skating — hold on if balance needs help.',
    'Book a couples massage or spa half-day for deep calm.',
    'Drive to a small town you have never explored; café hop once there.',
    'Build a blanket fort at home with fairy lights and playlists.',
    'Volunteer together for a few hours — shared purpose bonds hearts.',
    'Arcade date: playful competition, share tickets for a silly prize.',
    'Wine-free vineyard tour or orchard visit in harvest season.',
    'Photography walk: capture ten things that feel like “us.”',
    'Attend a local theater play or improv show — shared laughter.',
    'Plan a breakfast-in-bed surprise on a lazy weekend.',
    'Take a scenic train or ferry ride with no destination pressure.',
    'Visit an aquarium or planetarium — wonder feels romantic.',
    'Host a fondue night: chocolate or cheese, choose your adventure.',
    'Go thrifting and pick one outfit piece for each other.',
    'Write wishes on paper lanterns or jars and read them aloud.',
    'Plan a “yes day” with a small budget and big imagination.',
    'Rent bikes and explore a trail ending at a lakeside bench.',
    'Couples yoga or stretching session — gentle, grounding.',
    'Attend a food festival and share every bite.',
    'Set up a backyard fire pit with s’mores and old stories.',
    'Take a cooking class: pasta, sushi, or desserts.',
    'Plan a surprise day trip to a waterfall or scenic overlook.',
    'Visit a Christmas market or seasonal fair hand in hand.',
    'Record a short video diary of your date — memory for later.',
    'Book a cozy cabin or boutique hotel for one night away.',
    'Go to a jazz lounge with mocktails if you prefer no alcohol.',
    'Create a scavenger hunt with inside jokes as clues.',
    'Plant something together — herbs, flowers, a tree if allowed.',
    'Attend a poetry open mic and dedicate a line to them afterward.',
    'Plan a themed dinner at home: Paris, Tokyo, or their dream city.',
    'Watch the sunrise with hot drinks and silence first, words second.',
    'Visit a cat café or animal shelter visit if you love gentle creatures.',
    'Go bowling or mini-golf — playful rivalry, sweet truce.',
    'Take a pottery mug home and use it on your next coffee date.',
    'Plan a photo-book page of your favorite moments together.',
    'Attend a lantern festival or night market with matching colors.',
    'Write love letters and exchange them to open on a future date.',
    'Plan a stargazing drive with their favorite snacks in the trunk.',
    'Recreate your first meeting place with a small upgrade: better dessert.',
    'End the night saying what you are grateful for about them — specific beats generic.',
  ];

  static String randomNext(int seed) => nextIdeas[seed % nextIdeas.length];
  static String randomKeep(int seed) => keepIdeas[seed % keepIdeas.length];
  static String randomDate(int seed) => dateIdeas[seed % dateIdeas.length];
}
